In [25]:
import pandas
import random
import numpy as np

features_set = pandas.read_csv("movie.features.txt", delim_whitespace=True, header=None)
movies_set = pandas.read_csv("movie.box_office.txt", delim_whitespace=True, header=None)

In [28]:
features_num = len(np.unique(features_set[2]))

In [3]:
movies_set

             0  1
0       975900  0
1     10408933  0
2       171005  0
3        77856  1
4       612710  0
5       156558  0
6      1364293  0
7       261237  0
8     12008535  0
9      4951456  0
10     5708633  0
11    12053509  0
12     7364373  0
13     7028314  0
14    12788657  0
15     3873713  0
16      164387  0
17    24282217  0
18     7767613  0
19      164388  0
20    22985953  0
21     3550323  0
22     1765938  1
23     1305819  0
24     1031231  0
25     6305925  0
26      196176  0
27      748616  0
28    31505444  0
29      336846  1
...        ... ..
8274   2450370  1
8275    675878  0
8276   3027347  0
8277   6456053  0
8278   5971762  0
8279  34478159  0
8280   1840870  1
8281   1138104  1
8282    883432  1
8283   6707631  1
8284  35028178  0
8285   3147170  0
8286  26254041  0
8287    181601  1
8288   6322722  0
8289  10149834  1
8290   2472440  0
8291   1789884  0
8292  22427855  0
8293  11823946  0
8294    303933  1
8295  25920477  1
8296   4492078  0
8297   6740261  0
8298   1191380  0
8299     54540  1
8300   7761830  0
8301   1918494  0
8302    664006  0
8303  26482675  0

[8304 rows x 2 columns]

In [4]:
movie_dict = dict(zip(movies_set[0], movies_set[1]))

In [5]:
movie_dict

{975900: 0,
 10408933: 0,
 171005: 0,
 77856: 1,
 612710: 0,
 156558: 0,
 1364293: 0,
 261237: 0,
 12008535: 0,
 4951456: 0,
 5708633: 0,
 12053509: 0,
 7364373: 0,
 7028314: 0,
 12788657: 0,
 3873713: 0,
 164387: 0,
 24282217: 0,
 7767613: 0,
 164388: 0,
 22985953: 0,
 3550323: 0,
 1765938: 1,
 1305819: 0,
 1031231: 0,
 6305925: 0,
 196176: 0,
 748616: 0,
 31505444: 0,
 336846: 1,
 3033993: 0,
 103021: 0,
 1940449: 0,
 6703617: 1,
 362719: 1,
 4459059: 0,
 3681139: 0,
 5549065: 1,
 171058: 0,
 2608958: 1,
 2546429: 0,
 31686022: 0,
 24416479: 0,
 12490207: 0,
 3883051: 0,
 1033297: 1,
 207680: 1,
 1858682: 0,
 7235116: 0,
 5254729: 0,
 19168185: 0,
 27504492: 0,
 20506905: 0,
 6004372: 0,
 12091274: 0,
 7582987: 0,
 24021571: 0,
 1226289: 0,
 3475071: 0,
 44218: 0,
 7752732: 0,
 3809621: 0,
 1307956: 0,
 2216254: 0,
 28530363: 0,
 30548208: 1,
 1964091: 1,
 6721185: 0,
 3917900: 0,
 22358819: 1,
 706803: 1,
 20206687: 0,
 1851703: 0,
 3917873: 0,
 444919: 0,
 3670013: 0,
 11599737: 0,
 1033477: 0,
 24300269: 0,
 28010827: 0,
 1097249: 0,
 6973699: 0,
 33096336: 0,
 9104619: 0,
 24207129: 0,
 4572965: 0,
 5884079: 1,
 399402: 1,
 22224559: 1,
 22342112: 0,
 4836072: 1,
 2121431: 0,
 736262: 0,
 4360088: 0,
 5240350: 0,
 32066330: 1,
 18195326: 0,
 12095072: 0,
 27383563: 1,
 5565338: 0,
 6244632: 0,
 1231856: 1,
 1612686: 0,
 31707381: 0,
 5080311: 0,
 8948959: 0,
 8610844: 0,
 2028217: 0,
 14613957: 0,
 4724834: 0,
 34055313: 0,
 1157158: 0,
 16647548: 0,
 3028248: 0,
 4501185: 0,
 5877719: 0,
 3059075: 0,
 142274: 0,
 26149260: 0,
 1871167: 0,
 18487239: 0,
 1217079: 0,
 10088120: 0,
 1472852: 1,
 6846215: 1,
 13194784: 0,
 12180811: 0,
 5566878: 0,
 5876575: 0,
 1480748: 0,
 2023704: 1,
 1480747: 0,
 683122: 1,
 9457642: 0,
 26723356: 0,
 7351283: 0,
 8219325: 1,
 62688: 0,
 468356: 0,
 1238065: 0,
 570743: 1,
 504242: 0,
 129295: 1,
 256337: 1,
 933349: 0,
 8987889: 0,
 10344059: 0,
 9088886: 1,
 5257643: 0,
 3511253: 1,
 7024876: 0,
 580994: 0,
 20700559: 1,
 5329751: 0,
 7641358: 0,
 20629940: 0,
 221489: 0,
 9906067: 0,
 103022: 0,
 2236141: 0,
 2080306: 0,
 2002258: 0,
 1481638: 0,
 18065848: 0,
 1598832: 0,
 2261407: 0,
 8719979: 0,
 3158499: 0,
 26554437: 1,
 22578492: 0,
 4600218: 0,
 31404359: 0,
 1853602: 0,
 327427: 0,
 6987479: 0,
 2292864: 0,
 154635: 0,
 685987: 1,
 8499528: 0,
 1663320: 0,
 74868: 0,
 25411775: 0,
 4605171: 0,
 22486844: 0,
 8695: 0,
 14291637: 1,
 275547: 0,
 28042876: 1,
 31351: 0,
 9340076: 0,
 8700683: 1,
 3176181: 0,
 1380482: 0,
 1456329: 1,
 25496318: 0,
 12585204: 0,
 1488066: 0,
 36353797: 0,
 30575: 1,
 33146132: 0,
 4278437: 0,
 685721: 0,
 142443: 0,
 8964541: 0,
 43307: 1,
 366111: 1,
 9459581: 0,
 8997652: 0,
 7421446: 0,
 25871790: 0,
 7482786: 0,
 445066: 1,
 4340789: 0,
 4788925: 0,
 29631957: 0,
 31958696: 0,
 46505: 1,
 7482708: 0,
 3112996: 0,
 706860: 0,
 2262096: 0,
 992455: 0,
 770083: 0,
 4406314: 0,
 8850105: 1,
 2651593: 0,
 31231485: 0,
 30854972: 0,
 1282593: 0,
 24373655: 0,
 17247457: 0,
 12260258: 0,
 32424995: 0,
 2100492: 1,
 23734853: 0,
 10183625: 0,
 161452: 0,
 993791: 1,
 113454: 0,
 5955514: 0,
 6961461: 1,
 3727473: 0,
 680361: 1,
 19787914: 1,
 17008283: 0,
 359571: 0,
 22144721: 1,
 10940332: 0,
 165106: 0,
 19024526: 0,
 2609169: 0,
 24515495: 0,
 3710183: 0,
 142457: 1,
 10915095: 0,
 186856: 1,
 21242801: 0,
 92582: 0,
 16955791: 0,
 12746610: 0,
 31839719: 0,
 32376025: 0,
 607444: 1,
 8983787: 0,
 1380313: 0,
 25981715: 0,
 30204919: 0,
 1345561: 0,
 2941852: 0,
 6446044: 1,
 17657295: 0,
 3333: 1,
 365039: 1,
 3662683: 0,
 1353277: 0,
 28763446: 1,
 5082327: 0,
 2476317: 0,
 11448113: 0,
 4515733: 0,
 6179154: 0,
 2296056: 1,
 26537809: 0,
 31417999: 0,
 226198: 1,
 29890894: 0,
 2795282: 0,
 2196420: 0,
 11455154: 0,
 7081414: 0,
 944471: 0,
 102026: 0,
 14169361: 0,
 4213154: 0,
 7771844: 0,
 703687: 1,
 8464511: 0,
 34611699: 0,
 9478308: 0,
 22438706: 0,
 1032643: 0,
 10377382: 0,
 476640: 0,
 18555435: 0,
 2043990: 0,
 545187: 1,
 492540: 0,
 2964227: 0,
 22667247: 0,
 4186478: 0,
 14104063: 0,
 277710: 1,
 146947: 1,
 22751: 0,
 27063955: 0,
 14421091: 0,
 3979809: 0,
 27504596: 0,
 441280: 0,
 2501824: 0,
 1164551: 0,
 10466696: 0,
 70428: 0,
 5620636: 0,
 12665133: 0,
 26030961: 0,
 2448736: 0,
 23982633: 0,
 16395026: 0,
 6480541: 0,
 447255: 0,
 36353754: 0,
 28722503: 1,
 3343617: 0,
 4940876: 0,
 1749093: 1,
 29373289: 1,
 2117473: 0,
 27451281: 1,
 12267883: 0,
 25452802: 0,
 2045991: 0,
 30413435: 0,
 1638112: 0,
 29034714: 0,
 8620409: 0,
 22995027: 0,
 61501: 0,
 2352505: 0,
 2772142: 0,
 3450583: 1,
 7362782: 0,
 1136182: 0,
 11195154: 0,
 6342627: 0,
 2485103: 0,
 532618: 1,
 26978561: 0,
 3374650: 0,
 6976850: 0,
 9723255: 0,
 10806577: 0,
 7160018: 0,
 26514248: 0,
 920613: 1,
 2372994: 1,
 10499315: 0,
 22318957: 0,
 2513887: 0,
 5843155: 0,
 2165760: 0,
 6954370: 0,
 4179778: 0,
 2037403: 0,
 60164: 0,
 32683873: 1,
 26640605: 0,
 22291276: 0,
 3869472: 0,
 10815122: 0,
 2200771: 0,
 7330661: 1,
 10061978: 1,
 1356982: 1,
 3934285: 0,
 1073955: 1,
 3920193: 1,
 5800622: 0,
 1364770: 1,
 4143719: 0,
 541642: 1,
 2528212: 1,
 2082089: 0,
 10328139: 0,
 23961650: 0,
 201448: 1,
 350629: 0,
 4018828: 1,
 709318: 1,
 21404478: 0,
 320502: 0,
 20472949: 0,
 320500: 0,
 12929714: 0,
 9822793: 0,
 129602: 1,
 6257968: 1,
 2929705: 0,
 243204: 0,
 633832: 0,
 5305513: 0,
 2763233: 0,
 1232511: 0,
 2311219: 1,
 1118809: 1,
 27756613: 0,
 3007634: 0,
 23135176: 1,
 76335: 0,
 561315: 0,
 2302751: 0,
 3096943: 0,
 4694464: 0,
 1751944: 0,
 22267013: 0,
 2506848: 0,
 16125220: 0,
 26342915: 0,
 897540: 0,
 26717073: 1,
 12433713: 0,
 18098742: 0,
 369682: 1,
 26137623: 0,
 9415710: 0,
 1056686: 0,
 3681867: 0,
 32832973: 0,
 1041202: 0,
 36190244: 0,
 18949985: 0,
 24771643: 0,
 979825: 0,
 11745593: 0,
 18798887: 0,
 18571859: 1,
 2295405: 0,
 1054845: 0,
 30607472: 0,
 1278961: 0,
 887457: 1,
 2885102: 0,
 29358654: 0,
 6446874: 0,
 1830725: 1,
 8938294: 0,
 18599377: 0,
 1358544: 0,
 20370386: 0,
 4440277: 0,
 4586623: 0,
 8055976: 0,
 4857566: 0,
 2522220: 0,
 3978163: 1,
 30407971: 0,
 8929476: 0,
 1062036: 0,
 26138037: 0,
 1044875: 1,
 213471: 0,
 30865203: 0,
 14170318: 0,
 31403745: 0,
 23652051: 1,
 2032676: 0,
 6492614: 1,
 1102282: 0,
 23594997: 1,
 32869134: 0,
 14790659: 1,
 11697273: 0,
 17365387: 0,
 3671998: 0,
 27511014: 0,
 3840504: 0,
 6090730: 1,
 2571604: 1,
 15726696: 1,
 5579762: 0,
 2814516: 0,
 534778: 0,
 24978786: 0,
 20535192: 0,
 347235: 0,
 23784006: 1,
 30553238: 1,
 18716845: 0,
 20688153: 1,
 31371925: 0,
 6767366: 0,
 15122117: 1,
 1129583: 1,
 648921: 1,
 2825783: 0,
 644845: 0,
 1544670: 0,
 16751513: 0,
 174560: 0,
 10827382: 0,
 2887314: 0,
 2932827: 0,
 14812466: 0,
 73460: 1,
 1898116: 1,
 9907431: 0,
 33382022: 0,
 16072264: 0,
 9309429: 0,
 21427848: 0,
 1357356: 0,
 3140828: 0,
 8753860: 0,
 31192915: 0,
 945305: 0,
 12361350: 0,
 842825: 0,
 12839891: 0,
 17404922: 0,
 13861985: 0,
 26968376: 0,
 1681132: 1,
 1660125: 0,
 2254896: 0,
 12099955: 0,
 2372989: 0,
 35766264: 0,
 6218427: 0,
 2701438: 0,
 21032415: 0,
 13814165: 1,
 19583175: 0,
 2706104: 0,
 876592: 0,
 1631497: 1,
 36243056: 0,
 34480764: 1,
 2547451: 0,
 1524596: 1,
 27754718: 1,
 5010137: 0,
 12985644: 0,
 14281865: 0,
 3569329: 0,
 633883: 1,
 323715: 1,
 3105139: 1,
 13013743: 0,
 31667694: 0,
 21088389: 1,
 8776448: 0,
 1848371: 1,
 231829: 1,
 948223: 0,
 1745419: 0,
 705267: 0,
 3606413: 0,
 10206962: 0,
 624505: 0,
 2450545: 0,
 28847751: 0,
 2705562: 0,
 27328338: 0,
 23716980: 0,
 31754231: 1,
 20669402: 0,
 921891: 1,
 4399897: 0,
 15703454: 0,
 876872: 1,
 35874076: 1,
 31272988: 1,
 443556: 1,
 8284347: 0,
 798584: 0,
 2623071: 0,
 573304: 0,
 1853921: 1,
 886892: 0,
 303847: 0,
 5721992: 1,
 6443785: 0,
 11505804: 0,
 2241842: 0,
 1570843: 0,
 833502: 0,
 9653770: 0,
 34600874: 0,
 818002: 1,
 2137591: 0,
 27490108: 0,
 23092448: 1,
 9315177: 0,
 6095252: 0,
 24652963: 0,
 339526: 0,
 961777: 0,
 2541839: 1,
 98508: 0,
 5920233: 0,
 8538110: 0,
 5883086: 0,
 10753947: 1,
 7400070: 0,
 3422774: 0,
 98506: 0,
 14795399: 0,
 1267713: 1,
 26428662: 0,
 2159529: 1,
 565318: 1,
 6034681: 0,
 1384107: 1,
 2559661: 0,
 600194: 0,
 3238135: 0,
 14872132: 0,
 50957: 1,
 2037842: 0,
 1655618: 0,
 23266073: 1,
 24228929: 1,
 189776: 0,
 31918569: 0,
 28174450: 1,
 26188042: 0,
 19221106: 0,
 17366149: 0,
 24201336: 0,
 4434274: 0,
 133622: 0,
 1380618: 0,
 2886036: 1,
 3584478: 0,
 450634: 1,
 3412648: 1,
 2129381: 1,
 2647404: 0,
 2074330: 0,
 26488721: 0,
 2055559: 0,
 16102322: 0,
 8880229: 0,
 238906: 0,
 26316286: 0,
 6934510: 0,
 2354228: 0,
 13399638: 0,
 1223359: 0,
 10612031: 0,
 4760936: 1,
 12131002: 0,
 13264461: 0,
 1011468: 1,
 31893898: 0,
 3447166: 0,
 3842309: 1,
 29499533: 0,
 431562: 1,
 2676861: 0,
 5256717: 0,
 16749397: 0,
 1519783: 1,
 23461433: 0,
 33946021: 0,
 14281617: 0,
 164365: 1,
 7651220: 0,
 2518695: 0,
 1710716: 1,
 3371111: 0,
 29434234: 1,
 227291: 1,
 129368: 1,
 25430565: 0,
 2018921: 1,
 21380964: 0,
 17082042: 0,
 5549799: 0,
 2473101: 1,
 1412408: 0,
 4731904: 0,
 27731736: 1,
 28387210: 0,
 16143062: 0,
 23883858: 1,
 68124: 1,
 9251754: 0,
 3471023: 0,
 1474328: 1,
 29585929: 0,
 22430724: 1,
 171559: 0,
 1344253: 1,
 468326: 1,
 20509157: 0,
 3699824: 0,
 3038038: 1,
 916576: 0,
 24013376: 0,
 7657211: 0,
 1588930: 0,
 4228739: 0,
 2162986: 1,
 348292: 0,
 1316128: 0,
 8705561: 0,
 168498: 0,
 214783: 0,
 4073660: 0,
 5807082: 1,
 2520368: 0,
 529276: 1,
 10533451: 0,
 10640380: 0,
 17294536: 0,
 5578994: 0,
 20926831: 0,
 30329264: 0,
 3871584: 0,
 1076567: 0,
 430216: 0,
 1010466: 0,
 35575079: 0,
 187720: 0,
 18243264: 0,
 75255: 0,
 9782726: 0,
 22628938: 0,
 29296535: 0,
 706047: 1,
 3677015: 1,
 20906855: 0,
 3059082: 0,
 24731602: 0,
 1841530: 0,
 35654419: 0,
 12191026: 0,
 18943833: 1,
 5588165: 0,
 897481: 0,
 1377427: 1,
 210224: 1,
 19105706: 0,
 5813191: 0,
 4681364: 0,
 12000999: 1,
 13631232: 0,
 4299486: 0,
 5566494: 0,
 779536: 0,
 3591801: 0,
 1792785: 0,
 2973523: 0,
 2871613: 1,
 24709102: 0,
 29130076: 0,
 394792: 0,
 32411644: 0,
 3145613: 0,
 21231406: 0,
 7463646: 0,
 858575: 1,
 73376: 0,
 1848081: 0,
 33757147: 0,
 4926508: 0,
 1035959: 1,
 5702474: 0,
 716738: 1,
 454655: 1,
 434738: 0,
 61160: 0,
 2396120: 0,
 20238479: 0,
 1598996: 0,
 32790377: 0,
 1485962: 1,
 1942317: 1,
 2958168: 0,
 9391085: 1,
 33245032: 0,
 2546472: 0,
 1291587: 0,
 2161511: 0,
 20541936: 0,
 236122: 1,
 11253233: 0,
 5579274: 0,
 14727566: 0,
 3635829: 0,
 10189121: 0,
 26723019: 0,
 2461592: 1,
 11671832: 0,
 1430376: 0,
 28648635: 1,
 29170556: 0,
 14828868: 0,
 30872649: 0,
 30273553: 1,
 314775: 0,
 12764922: 0,
 13920598: 1,
 3037303: 0,
 18895020: 0,
 6578384: 0,
 1975939: 0,
 21742948: 0,
 7255312: 1,
 17726219: 0,
 805053: 0,
 31795894: 1,
 12375241: 0,
 2241866: 0,
 2190622: 1,
 22044760: 0,
 26695339: 1,
 1329111: 0,
 525270: 1,
 9661361: 0,
 17997162: 1,
 7643463: 0,
 2298243: 0,
 5083366: 0,
 24563042: 0,
 12765279: 0,
 6856644: 0,
 465470: 1,
 1679437: 0,
 8781770: 0,
 18593635: 0,
 5352769: 0,
 29502933: 0,
 19011948: 0,
 27792643: 0,
 15516110: 0,
 27434686: 0,
 8964687: 0,
 32340746: 1,
 1176717: 0,
 1962219: 0,
 6632229: 0,
 6559110: 0,
 286850: 0,
 576204: 0,
 2426058: 0,
 870946: 1,
 25757091: 0,
 9823573: 0,
 1235519: 0,
 13473620: 0,
 1123132: 0,
 338849: 0,
 34312285: 1,
 1820344: 0,
 5570618: 0,
 7893461: 0,
 27384074: 0,
 10249080: 1,
 5579355: 0,
 1863523: 0,
 1072075: 1,
 6575053: 0,
 1503652: 0,
 3292569: 0,
 473253: 1,
 224224: 0,
 348449: 1,
 28794755: 0,
 23968261: 0,
 707823: 0,
 1376896: 0,
 30400320: 0,
 4440305: 0,
 2002403: 0,
 61049: 0,
 3649048: 0,
 16937946: 0,
 5336170: 0,
 2108445: 0,
 1486573: 0,
 173944: 1,
 17578623: 0,
 2935497: 1,
 20513862: 0,
 19942818: 1,
 193867: 0,
 10035818: 0,
 8633676: 0,
 9897904: 0,
 31905391: 1,
 2075820: 0,
 3368653: 0,
 1409356: 1,
 2637077: 1,
 2815064: 0,
 5893524: 0,
 6097745: 0,
 722551: 0,
 20072102: 0,
 30448518: 0,
 2233095: 1,
 1032620: 1,
 7892732: 1,
 28480541: 0,
 1740284: 0,
 2010489: 0,
 4981484: 0,
 15120787: 0,
 1801788: 0,
 33887035: 1,
 587507: 0,
 1883157: 0,
 3396134: 0,
 99459: 1,
 35432986: 0,
 8448026: 0,
 3228403: 0,
 15161999: 1,
 402866: 1,
 20185209: 0,
 23141724: 0,
 15815398: 0,
 23555063: 0,
 24854885: 0,
 511228: 1,
 3193295: 0,
 32791398: 0,
 11715286: 0,
 2572919: 1,
 1389264: 0,
 27087967: 0,
 34611534: 0,
 29007186: 1,
 2313660: 0,
 1188061: 0,
 3952475: 0,
 25737142: 1,
 35729649: 0,
 957792: 1,
 3256132: 0,
 2245886: 1,
 2282187: 0,
 2387927: 0,
 33577424: 1,
 1239400: 1,
 25183229: 0,
 7455727: 0,
 31941863: 0,
 172577: 1,
 171522: 0,
 4429283: 0,
 24445186: 1,
 15332396: 1,
 574909: 0,
 5638447: 0,
 103026: 1,
 8675614: 0,
 1052246: 0,
 277667: 1,
 76366: 0,
 2673183: 0,
 2810158: 1,
 187616: 0,
 9377241: 0,
 2955883: 0,
 3673758: 0,
 890407: 0,
 28272795: 1,
 26931217: 1,
 9317122: 0,
 17816459: 0,
 1172977: 0,
 2236324: 1,
 187010: 1,
 30874145: 0,
 193854: 0,
 19887961: 0,
 2542108: 0,
 14482638: 1,
 1180124: 0,
 3918828: 0,
 25893091: 0,
 15497901: 0,
 950429: 0,
 8057560: 0,
 3602324: 0,
 364541: 0,
 29471340: 1,
 ...}

In [6]:
hits_set = movies_set[movies_set[1] == 1]

In [7]:
hits_set

             0  1
3        77856  1
22     1765938  1
29      336846  1
33     6703617  1
34      362719  1
37     5549065  1
39     2608958  1
45     1033297  1
46      207680  1
65    30548208  1
66     1964091  1
69    22358819  1
70      706803  1
86     5884079  1
87      399402  1
88    22224559  1
90     4836072  1
95    32066330  1
98    27383563  1
101    1231856  1
123    1472852  1
124    6846215  1
130    2023704  1
132     683122  1
136    8219325  1
140     570743  1
142     129295  1
143     256337  1
147    9088886  1
149    3511253  1
...        ... ..
8209   1695109  1
8213    142421  1
8216   1246394  1
8218     94028  1
8219   4443534  1
8221    174251  1
8223   2323962  1
8225   3123893  1
8227  15349469  1
8229   3759215  1
8231  20926377  1
8241    454208  1
8242    531747  1
8245  16578764  1
8247   2392280  1
8252   2303174  1
8257    972958  1
8260  31052221  1
8262    699336  1
8264   1042309  1
8274   2450370  1
8280   1840870  1
8281   1138104  1
8282    883432  1
8283   6707631  1
8287    181601  1
8289  10149834  1
8294    303933  1
8295  25920477  1
8299     54540  1

[2078 rows x 2 columns]

In [8]:
yes_goodman_set = features_set[features_set[0] == "John_Goodman"]

In [9]:
yes_goodman_set

                  0  1         2
115    John_Goodman  1   1305819
1065   John_Goodman  1    770083
1739   John_Goodman  1    920613
2495   John_Goodman  1   8753860
2921   John_Goodman  1   2541839
3161   John_Goodman  1    238906
3691   John_Goodman  1   3145613
4239   John_Goodman  1   5336170
6239   John_Goodman  1   6978596
7186   John_Goodman  1   8737659
7888   John_Goodman  1   4628762
8601   John_Goodman  1  31701975
10020  John_Goodman  1   5943254
11902  John_Goodman  1   5752544
12332  John_Goodman  1    725817
13207  John_Goodman  1   3210303
13442  John_Goodman  1   1151458
13529  John_Goodman  1   4835894
13648  John_Goodman  1   6141751
14368  John_Goodman  1   1138831
14378  John_Goodman  1  12781074
15605  John_Goodman  1   2910440
16242  John_Goodman  1  25230514
16280  John_Goodman  1    197558
16541  John_Goodman  1  12149364
17334  John_Goodman  1   1170663
17551  John_Goodman  1   2361396
20172  John_Goodman  1   2988222
20553  John_Goodman  1    848218
20627  John_Goodman  1   4718224
20916  John_Goodman  1  29491325
20952  John_Goodman  1   2576917
20972  John_Goodman  1   6215998
21010  John_Goodman  1  33028800
21370  John_Goodman  1  30578340
21425  John_Goodman  1  19250235
21722  John_Goodman  1  10272267
21930  John_Goodman  1    328344
23265  John_Goodman  1     29782
24165  John_Goodman  1    279813
24650  John_Goodman  1  20699587
24964  John_Goodman  1    341399
26691  John_Goodman  1  34414967
27229  John_Goodman  1    170858
27396  John_Goodman  1    348356
27564  John_Goodman  1    932407
28040  John_Goodman  1    320401
28485  John_Goodman  1     22216
30473  John_Goodman  1   8867686
31691  John_Goodman  1    560837
32185  John_Goodman  1    338869
35499  John_Goodman  1   2700693
35944  John_Goodman  1  10837755
36037  John_Goodman  1  17112291
36178  John_Goodman  1   5002289
36634  John_Goodman  1  31804949
37677  John_Goodman  1    825149
37954  John_Goodman  1   2863319
38760  John_Goodman  1    194664

In [11]:
goodman_hits = 0
for item in yes_goodman_set[2]:
    goodman_hits +=movie_dict[item]
goodman_hits_mean = goodman_hits/len(yes_goodman_set)
goodman_hits_mean

0.40677966101694918

In [45]:
no_goodman_hits = (len(hits_set) - goodman_hits)
no_goodman_hits

2054

In [46]:
no_goodman_films = (features_num)-len(yes_goodman_set)
no_goodman_films

8245

In [47]:
no_goodman_hits_mean = no_goodman_hits/no_goodman_films
no_goodman_hits_mean

0.24912067919951486

In [48]:
features_num

8304

In [49]:
len(yes_goodman_set)

59

In [17]:
len(hits_set)

2078

In [10]:
len(hits_set) - goodman_hits

2054

Now, let's calculate our observed test statistic of interest

In [50]:
t = goodman_hits_mean - no_goodman_hits_mean
t

0.15765898181743432

Now, let's calculate I for p

In [59]:
b = 0
i = 0
random_t1_mean = 0
random_t2_mean = 0
random_t = 0
all_hits_sum = sum(movie_dict.values())

while b <= 10000:
    
    permuted_t1 = random.sample(list(movie_dict), len(yes_goodman_set)) # 59 random movie ids (=movies with Goodman)
    t1 = 0
    for key in permuted_t1:
        t1 +=movie_dict[key] # sum up values at these keys and get the number of hits

    random_t1_mean = t1/len(yes_goodman_set) # proportion of hits in a random sample to all goodman movies
    random_t2_mean = (all_hits_sum-t1)/no_goodman_films # proportion of hits in a random sample to all non-goodman movies

    random_t = random_t1_mean - random_t2_mean

    if abs(t) <= abs(random_t):
        i +=1
    b+=1

In [60]:
i

66

In [61]:
p = i/b
p

0.0065993400659934

**Can the null hypothesis (that movies featuring John Goodman have the same proportion of box office hits as those that do not) be rejected with a significance level of alpha = 0.01? If so, what is the size and direction (positive or negative) of the effect?**

As our permutation test proves, the probability of seeing a test statistic as extreme as 0.35451 is less than 1% (0.007). With significance level 0.01 **we therefore regect the null hypothesis**. Since the difference between mean for hits with Goodman and mean for hits without Goodman is a positive number (0.354) **the direction is positive**. The effect size is the difference between the observed statistic t and null hypothesist which is 0 (because under null hyp the difference is 0). **The effect size equals 0.354.**